- app/renderer/actions/Session.js
edit ssl config for roboticmobi provider
> feat: edit roboticmobi ssl config

- app/renderer/components/Session/Session.css
@jlipps  I have the same problem.
#59 he said the **_inspector window_**, means the **_Session_** page.
> fix: can not move window.

- app/renderer/actions/Inspector.js
- app/renderer/actions/Session.js
- app/renderer/components/Inspector/Actions.js
- app/renderer/components/Inspector/ElementLocator.js
- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Inspector/Inspector.js
- app/renderer/components/Inspector/SelectedElement.js
- app/renderer/components/Inspector/shared.js
- app/renderer/components/Session/CapabilityControl.js
- app/renderer/components/Session/CapabilityEditor.js
- app/renderer/components/Session/FormattedCaps.js
- app/renderer/components/Session/Session.js
- app/renderer/reducers/Inspector.js
- assets/locales/en/translation.json
- package-lock.json
- package.json
Trying to fix a bunch of small issues I've noticed
> Misc updates and fixes

- README.md
adding robotic.mobi links to README.md
> robotic.mobi: add links to supported cloud platforms

- app/renderer/actions/Session.js
Hi @KazuCocoa 
I have patched the fix for https://github.com/appium/appium-inspector/issues/133.
Can you you please help me review this PR?
Thanks,
> Fix: Can't launch test session with Kobiton  #133

- app/renderer/lib/client-frameworks/framework.js
- app/renderer/lib/client-frameworks/java.js
- app/renderer/lib/client-frameworks/js-wd.js
- app/renderer/lib/client-frameworks/js-wdio.js
- app/renderer/lib/client-frameworks/python.js
- app/renderer/lib/client-frameworks/robot.js
- app/renderer/lib/client-frameworks/ruby.js
https://github.com/appium/appium-inspector/issues/251
The `codeFor_switchContexts` must be `codeFor_switchContext`.
> fix template code for switch context

- app/renderer/lib/client-frameworks/python.js
- app/renderer/lib/client-frameworks/ruby.js
https://github.com/appium/appium-inspector/issues/226
Updating Python template code for client v2
> feat: update python template code

- app/renderer/lib/client-frameworks/python.js
output example:
```
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(321, 354)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.move_to_location(72, 361)
actions.w3c_actions.pointer_action.release()
actions.perform()
```
> feat: update gesture in python for w3c

- package-lock.json
- package.json
Reverts appium/appium-inspector#250
> Revert "chore(deps): bump react-router from 5.2.1 to 6.2.1"

- app/renderer/actions/Session.js
To reduce logs in a browser console.
> chore: adjust log level

- .gitignore
- app/renderer/lib/client-frameworks/java.js
@jlipps Please review.  Let me know if you need anything else.
> feat: update to use PointOption class in Java

- app/renderer/actions/Session.js
fixes https://github.com/appium/appium/issues/15132
2 minutes isn't cutting it for Sauce Labs :(
> fix: boost commandRetryTimeout from 2 to 5 minutes

- app/renderer/actions/Inspector.js
- app/renderer/components/Inspector/HighlighterRect.js
- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Inspector/LocatedElements.js
- app/renderer/components/Inspector/LocatorTestModal.js
In this PR, the inspector search feature has been improved in terms of, elements in the landing page are highlighted when searched. The front-end feature of the Locator Modal has been improved, specifically the back button and the no elements found page.
> Improved Appium-Inspector Search Feature

- app/renderer/actions/Session.js
this is an attempt to pull in @enkryptor's work in #270
> fix: protect against unset SAVED_SESSIONS

- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Inspector/SelectedElement.js
This PR Closes #137 
Added the ability to allow users to click on any element attributes/selectors and have it automatically copied to their clipboard!
> feat: copy to clipboard by click on a value

- app/renderer/actions/Inspector.js
- app/renderer/actions/Session.js
- app/renderer/components/Inspector/HighlighterRects.js
- app/renderer/components/Inspector/Inspector.js
- app/renderer/components/Inspector/Screenshot.js
- app/renderer/lib/appium-client.js
- app/renderer/reducers/Inspector.js
if the mjpegScreenshotUrl cap is included, we can use that
for a more real time screen view, and forego getting screenshot
> feat: show mjpeg stream instead of static screenshot

- app/renderer/actions/Inspector.js
- app/renderer/components/Inspector/Inspector.js
- app/renderer/components/Inspector/SessionCodeBox.js
- app/renderer/components/Inspector/SessionInfo.js
- app/renderer/components/Inspector/shared.js
- app/renderer/reducers/Inspector.js
- package-lock.json
- package.json
This PR Closes #416 
In this feature the user will have the ability to retrieve information about the currently running session once they've started inspecting.
> feat: session info panel

- app/renderer/components/Session/Session.css
This fixes https://github.com/appium/appium-inspector/issues/525
This might be pretty important for people who downloaded the latest version. They are stuck now if the list is bigger than 10 stored sessions
> Fix issue 525

- app/main.js
- app/main/menus.js
this change depends on https://github.com/appium/appium-gui-libs/pull/5 and will fail to build until that is merged and the submodule ref updated here.
this PR closes #520
> feat: allow multiple new session windows

- app/renderer/lib/client-frameworks/robot.js
Fixing the issue and adding a tip for the first test to pass
> Fixing the issue https://github.com/appium/appium-inspector/issues/578

- app/renderer/components/Session/Session.js
Updating the capability documentation link
> fix: the issue https://github.com/appium/appium-inspector/issues/603

- app/renderer/actions/Inspector.js
- app/renderer/components/Inspector/Inspector.js
- app/renderer/components/Inspector/Source.js
- app/renderer/reducers/Inspector.js
- package-lock.json
it is sometimes useful to be able to see everything that is there, particularly in web mode
> feat: add button to toggle showing of all attributes in source

- app/renderer/lib/client-frameworks/js-wd.js
real life usage of the recorder application,
Where the user isn't instantly having buttons be visible.
> I added an implicit wait in the recorder to match more

- .gitignore
- app/renderer/reducers/Session.js
> fix: save button not enabled after editing raw capability json

- app/renderer/lib/client-frameworks/js-wdio.js
Fixes #531 
Updated the webdriverio client methods based on the Docs https://webdriver.io/docs/api/
> fix: update client framework code generation for webdriverio.js

- app/renderer/lib/client-frameworks/robot.js
Updating Tap keyword to Tap With Positions, and adding 4spaces to keywords generated, because we always use the generate code into a test case....
> Fixing the issue #695

- app/renderer/lib/appium-client.js
> Fixed: #699 Appium Inspector not working correctly whith Espresso

- package-lock.json
- package.json
To release a few changes since last update
cc @jlipps
> chore: 2023.2.1

- .github/workflows/pr-validation
I'll merge this once, and create a followup PR to modify this script
> ci: move pr validation from azure to github actions

- .github/workflows/node.build.yml
The current CI on master is getting failure. Let me tweak something
> ci: update node

- app/renderer/actions/Inspector.js
> skip recording for status

- package-lock.json
To fix CI first. I have kept the package version as 2023.4.1
> fix: revert packag-lock update to fix CI

- app/renderer/lib/client-frameworks/framework.js
Fixes https://github.com/appium/appium-inspector/issues/770
> fix: do not add / if the remote path was /

- app/renderer/components/Inspector/shared.js
- assets/locales/en/translation.json
> fix: remove deprecated Reset App action

- app/renderer/components/Inspector/LocatedElements.js
Quick refactor after discussion under #849.
> chore: refactor highlight request fix

- package-lock.json
This PR is the result of running `npm audit fix`. Main reason why I ran it is because I saw 8 critical vulnerabilities, and this command removed the affected module entirely.
> chore(deps): fix several vulnerabilities

- app/renderer/actions/Session.js
Realized that showing the error is not enough!
> fix: when attach session fails, actually short circuit due to error

- app/renderer/components/Inspector/Commands.js
> fix: dereference pending command object correctly

- package-lock.json
- package.json
Reverts appium/appium-inspector#430
> Revert "chore(deps): update dependency cheerio to v1.0.0-rc.12"

- package-lock.json
- package.json
- test/e2e/inspector-e2e.test.js
- test/integration/client-actions.integration-test.js
> chore(deps): update dependency @appium/fake-driver to v5.3.0

- README.md
Documentation site is being migrated to new address.
> docs: update Mobitru docs link

- .github/release.yml
This configuration file will provide prettier release notes.
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
> chore: add configuration for release notes

- app/renderer/components/Inspector/SavedGestures.js
- app/renderer/components/Inspector/SelectedElement.js
- app/renderer/components/Inspector/SessionInfo.js
- app/renderer/components/Session/AttachToSession.js
- app/renderer/components/Session/CapabilityControl.js
- app/renderer/components/Session/CapabilityEditor.js
- app/renderer/components/Session/FormattedCaps.js
- app/renderer/components/Session/SavedSessions.js
- app/renderer/components/Session/ServerTabPerfecto.js
- assets/locales/en/translation.json
This PR adds translation keys for various previously hardcoded strings. With this, I believe all text strings should now be changed to translation keys.
> fix: add remaining translation keys

- README.md
I think it would be nice to address possible removal in case they are not compatible with our inspector.
https://github.com/appium/appium-inspector/issues/391
> docs: address possible removal in cloud providers

- .github/release.yml
This adds a new localization section in the autogenerated release notes.
> chore: add localization section in release notes

- app/renderer/components/Session/SavedSessions.js
> fix: resolve 't' error on saved caps tab

- app/renderer/src/assets/locales/en/translation.json
- app/renderer/src/components/Inspector/Inspector.module.css
- app/renderer/src/components/Inspector/LocatedElements.jsx
> feat: add locator details to find element results

- package.json
- renovate.json
* add electron-debug to Renovate's blocked major releases list
* add comments in package.json for more blocked dependencies
> chore: update blocked dependency info

- ci-jobs/crowdin-common.mjs
Fix for #1514 where one path change was missed.
> fix: adjust Crowdin sync path

- app/env.js
Removes one extra file that was missed in #1407.
> chore: remove unused env file

- app/common/lib/client-frameworks/dotnet-nunit.js
> fix: adjust syntax for .NET codegen

- app/common/renderer/actions/Session.js
Fixes https://github.com/appium/appium-inspector/issues/1652
Thanks to @eglitise for his help! 
More detailed info is explained in https://github.com/appium/appium-inspector/pull/1369#discussion_r1508864543
> chore: fix support for `Attach to Session` for LambdaTest server

- app/common/renderer/actions/Session.js
- app/common/renderer/utils/attaching-to-session.js
- test/unit/utils-attaching-to-session.spec.js
This PR is a follow-up to #1632 and adds support for attaching to Appium sessions running under Selenium Grid.
Resolves #287.
> feat: support attaching to Selenium Grid sessions

- package-lock.json
This rebuilds the package-lock.json file by running `npm run clean:npm`, which fixes all remaining known project vulnerabilities.
> chore(deps): rebuild lockfile

- package-lock.json
- package.json
Reverts appium/appium-inspector#1720
> Revert "chore(deps): update dependency cheerio to v1.0.0"

- docs/index.md
- docs/menu-bar.md
- docs/overview.md
- docs/quickstart/requirements.md
- docs/quickstart/starting-a-session.md
- docs/session-builder/capability-builder.md
- docs/session-builder/index.md
- docs/session-builder/saved-capability-sets.md
- docs/session-builder/server-details.md
- docs/session-inspector/commands.md
- docs/session-inspector/gestures.md
- docs/session-inspector/header.md
- docs/session-inspector/index.md
- docs/session-inspector/recorder.md
- docs/session-inspector/source.md
- docs/troubleshooting.md
- package-lock.json
- package.json
Replaces #1821 and includes additional Markdown changes to align with Prettier 3.4.
> chore(deps): update dependency prettier to v3.4.1

- index.js
- package.json
- plugins/index.js
- plugins/package-lock.json
- plugins/package.json
- applied prettier
- fixed the `build:plugin`
> update proto-plugin branch

- plugins/README.md
@KazuCocoa made readme better. Please review
> updated readme for plugin

- docs/quickstart/installation.md
I forgot that the lint/format job does not run for documentation changes. Will fix this in another PR.
> chore: run prettier

- README.md
> docs: update RobotQA docs link

- app/common/renderer/actions/Session.js
Fixes an issue where the showError function could not destructure the server URL
> fix: Fix URL in error notification

- .github/workflows/package.yml
For `secrets.GITHUB_TOKEN` as https://github.com/appium/appium-xcuitest-driver/pull/2593
> ci: add explicit write permission

- renovate.json
> chore: update Renovate config
