- app/renderer/actions/Session.js
- app/renderer/components/Session/NewSessionForm.js
- app/renderer/reducers/Session.js
- assets/locales/en/translation.json
- copy-en-i18n.js
- package-lock.json
This should help folks migrate to Appium 2.0 by automatically updating their caps with a prefix unless they deselect the checkbox.
> feat: add checkbox to allow updating of caps with vendor prefixes

- app/renderer/actions/Session.js
- app/renderer/components/Session/Session.js
- app/renderer/reducers/Session.js
- test/e2e/inspector-e2e.test.js
This will enable us to automatically set state for ADI via a deep link or a regular URL (in browser mode)
> feat: enable state init and auto-start-session via the query string

- app/renderer/actions/Session.js
I guess https://github.com/appium/appium-inspector/pull/118#issuecomment-914027306 did not use `username` and `accessKey` as their basic auth.
> Fix conns use key

- app/renderer/actions/Session.js
**Issue**
Currently, on using the appium-inspector we get the following error.
**Fix**
Use `bstack:options` for setting the 'source' capability for BrowserStack to comply with W3C spec.
> Use bstack:options for setting the 'source' capability for BrowserStack to comply with W3C

- app/renderer/actions/Session.js
robotic.mobi: adding options 'source' capability
> robotic.mobi: adding options 'source' capability

- app/renderer/actions/Session.js
`new URL()` does not have the port for `https://xxx:443/` and `http://xxx:80` cases
> fix: default http/https port in hs

- app/renderer/actions/Session.js
There is currently a difference in drivers when a session is started through the Appium inspector and when a session is attached. 
The `commandList` are different which is a result of different `userPrototypes` being set up in webdriver. 
https://github.com/webdriverio/webdriverio/blob/e2aa001ecbf240e5240ce551acbfb19f6d004973/packages/webdriver/src/utils.ts#L182
When starting a session, webdriver will determine device type and configure the userPrototypes accordingly. However, when attaching to a session, webdriver doesn't do this which results in the difference in drivers. Since we are attaching to a session in the Appium Inspector, we can assume that the use cases are devices that are mobile so we set `isMobile = true` in the server options.
> fix: Ensure Appium Protocol is included when attaching to a session id

- app/renderer/actions/Session.js
* If "sauce:options" is not set, set it so that it defaults to W3C
* Give the Appium Desktop job a name so that it's easier for Sauce Labs users to know which job came from Appium Desktop
> include sauce:options by default and give job a name

- app/renderer/actions/Session.js
Current requests after attach to an existing session is default each end client's default timeout instead of webdriverio's default one.
As our future work, we could make them customizable, but let me make the timeout as same as webdriverio's default value for now.
For example, ky (browser) one is 10 sec. `/source` endpoint can take over the time easily.
> fix: add connectionRetryTimeout in attaching to an existing session

- app/renderer/actions/Inspector.js
- app/renderer/actions/Session.js
- app/renderer/lib/appium-client.js
- app/renderer/reducers/Inspector.js
This PR fixes the following things:
- The `applyClientMethod` method always returned an undefined result, due to an incorrect mapping
- When a session was started with a browser (Chrome/Safari) the source was automatically translated to HTML, but the app mode was still in "Native App Mode", see screenshot below. It will now already start in "Web/Hybrid AppMode"
- Switching between "Web/Hybrid AppMode", where the source is HTML, and "Native App Mode" didn't trigger:
- switching back to `NATIVE_APP`-mode
- a refresh of the source
This is now fixed and the native source code will be shown when "Native App Mode" is selected
- A tap was sometimes seen as a long press because it was set at 500ms, this PR changes it to 100ms which should be handled as a tap
> Multiple fixes

- package-lock.json
- package.json
Run npm install with NodeJS 14 (the ci also NodeJS 14).
lockfileVersion is also v2 for now.
I'll create a tag after this merge.
> chore: bump inspector version

- app/main/helpers.js
Current main raises an exception in the browser mode as an electron dependency.
This PR drops them since they no longer used in this repository.
> fix: fix to start browser by removing unused electron

- app/renderer/components/Inspector/shared.js
This PR fixes the setGeoLocation bug on Appium Inspector by updating the set GeoLocation with new arguments.
> fix: Unable to set geolocation in Appium inspector #210

- app/renderer/components/Inspector/Source.js
This PR fixes the page source not folding down when selecting an element in the screenshot box on the first load of the inspector.
> fix: when selecting element, source is not unfolded to show selected element #384

- app/renderer/actions/Session.js
supersedes #225, which got stalled due to CLA
> fix: bitbar connection

- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Inspector/Source.js
seems like it's confusing not to have visible system scrollbars when necessary.
> fix: restore scrollbars to source pane (fix #383; fix #194)

- app/renderer/components/Inspector/Inspector.js
This PR Closes #399 
Added a download icon in the source header to allow users to download the source as a .xml file. Also moved the 'copy XML source to clipboard' button in the source header!
> feat: ability to download source as a .xml file

- app/renderer/components/Session/CapabilityControl.js
- app/renderer/components/Session/CapabilityEditor.js
- app/renderer/components/Session/Session.css
This PR Closes #188 
Changed the font in the capabilities text boxes to monospace so that whitespaces are more apparent!
> feat: use monospace font in capability names and values so whitespace is obvious

- app/renderer/actions/Session.js
- app/renderer/components/Session/CapabilityEditor.js
- app/renderer/components/Session/SavedSessions.js
- app/renderer/components/Session/Session.js
- app/renderer/reducers/Session.js
This PR Closes #398 
In this PR whenever the user saves their capabilities, the remote connection details (this includes any cloud provider details or advanced settings) are saved as well. So the user can have many different capabilities saved, and when they click on the saved capabilities the remote session/cloud provider connection information associated with that particular CAP set is loaded as well.
> feat: save remote connection info alongside capabilities in saved sets

- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Inspector/SessionInfo.js
This PR fixes some bugs and frontend features of the session information panel. 
This includes: 
1.) Updating Session URL to display the correct URL: http://<host>:<port><path>/session/<session-id>
2.) Fixing some padding issues 
3.) Setting the session timer to update live instead of updating when user interacts with the UI
4.) Combining the server details into one row
5.) Removed the session CAPS row with session details, which now retrieves all session info from the webdriver.io command 'getSession'
However, I could not determine a way to display the scroll bar on default, still looking into antd docs to determine what properties need to change in order to accomplish that.
> fix: session panel info and padding

- app/renderer/lib/client-frameworks/python.js
This PR Closes #438 
This PR updates the code generated for python when finding an element using XPATH.
> fix: Appium recorder bug - Python code generated wrong for XPATH

- app/renderer/components/Inspector/Screenshot.js
This PR closes #480 
I removed the condition to check if x is null to allow taps to occur within the coordinate overlay on the top left when user is in the 'Tap by Coordinates' mode. This also allows the user to see the coordinate values within the overlay which I think will be useful!
> fix: Tap by coordinates does not work inside the current pointer coordinates overlay area 

- app/renderer/actions/Inspector.js
- app/renderer/components/Inspector/HighlighterCentroid.js
- app/renderer/components/Inspector/HighlighterRect.js
- app/renderer/components/Inspector/HighlighterRects.js
- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Inspector/Inspector.js
- app/renderer/components/Inspector/Screenshot.js
- app/renderer/components/Inspector/shared.js
- app/renderer/reducers/Inspector.js
- assets/locales/en/translation.json
This PR closes #276 
This PR seeks to improve the element selection within Appium Inspector by rendering all the elements as small centroids so users can see and highlight certain difficult elements. Square boxes represent non container elements, circle centroids represent containers, dashed green centroids/boxes represent elements not in the current hierarchy/overlapping elements, and the +/- circles are just expandable circles to show those overlapping elements.
> feat: improve element selection

- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Inspector/Screenshot.js
This PR Closes #530 
The overlay that shows the x and y values during a tap gesture within the inspector has now been fixed so that it shows the correct and accurate y-values. 
https://user-images.githubusercontent.com/85202734/181113730-b42c2302-4465-411b-8e2b-8830b0de7903.mov
> Fix: Tap by coordinates inside the coordinates overlay does not show correct Y values

- app/renderer/lib/client-frameworks/framework.js
- app/renderer/lib/client-frameworks/java.js
- app/renderer/lib/client-frameworks/js-oxygen.js
- app/renderer/lib/client-frameworks/js-wd.js
- app/renderer/lib/client-frameworks/js-wdio.js
- app/renderer/lib/client-frameworks/python.js
- app/renderer/lib/client-frameworks/robot.js
- app/renderer/lib/client-frameworks/ruby.js
The method for calling the various `codeFor_*` functions doesn't seem to be aligned with the way that the corresponding actions are constructed to execute a task. E.g., a swipe consists of _move, down, pause, release_, under a specific pointer, _finger1_. These functions are, instead, expecting x and y coordinates.
This patch add some util functions to the `Framework` class so that its subclasses can write the appropriate code for _tap_ and _swipe_ actions by unpacking the more complex pointer action object that is constructed elsewhere within the inspector.
fixes: #615
> fix: added utils for encoding tap/swip coords properly

- app/renderer/actions/Inspector.js
This interval is how often appium inspector sends getTimeouts request to keep the session alive.
The default newCommadnTimeout in appium inspector is 3600, so 5 sec is not necessary interval. 20 sec, or more also should be sufficient.
Potentially this will slightly improve https://github.com/appium/appium-inspector/issues/736
> chore: relax getTimeouts interval

- app/renderer/components/Inspector/Actions.js
- app/renderer/components/Inspector/GestureEditor.js
- app/renderer/components/Inspector/Inspector.js
- app/renderer/components/Inspector/LocatorTestModal.js
- app/renderer/components/Inspector/Screenshot.js
- app/renderer/components/Inspector/SelectedElement.js
- app/renderer/components/Session/CapabilityEditor.js
- app/renderer/components/Session/CloudProviderSelector.js
- app/renderer/components/Session/Session.js
This PR replaces some deprecated antd functionality:
* Tabs.TabPane -> Tabs.items
* Tooltip.visible -> Tooltip.open
* Modal.visible -> Modal.open
> chore: replace deprecated antd functionality

- app/renderer/actions/Session.js
This changes makes sure we do not override any `tb:options` specified by the user.
If a user entered their own `tb:options`, it should not be overridden.
> fix: do not override`tb:options` when specified

- app/renderer/components/Inspector/shared.js
- app/renderer/util.js
- package-lock.json
- package.json
- test/unit/util-specs.js
This PR extends #750 by updating to the latest @xmldom/xmldom version, and also updating the imports.
While @xmldom/xmldom v0.8.0 is labeled as a breaking change, I didn't encounter any issues with either unit tests or normal app source retrieval.
Note that xmldom 0.6 is still used in @appium/fake-driver, which will be covered separately.
> chore(deps): update xmldom to @xmldom/xmldom 0.8.7

- README.md
- app/renderer/actions/Session.js
- app/renderer/components/Inspector/DeviceActions.js
This PR fixes a few minor things in #746: 
* pause source refresh button
* turns out that if MJPEG stream is not used, toggling this button also stops refreshing screenshot - this has been added to the readme
* system buttons
* rename Android Overview button to App Switch, according to [Android Developer reference](https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_APP_SWITCH)
* swap keycodes for Android Back and Android Home buttons, also according to Android Developer reference
* add more details in readme
> chore: update readme and fix Android system buttons

- assets/locales/ru/translation.json
This is a minor fix for [commit e87bf9b](https://github.com/appium/appium-inspector/commit/e87bf9b393d8972725f23df5e59aa1f69073bd75).
Also, it seems that CI is failing (as it cannot build Inspector v2023.4.1). This is likely related to the package-lock changes in the same commit.
> fix: remove leftover 'savedSessionsCount'

- app/renderer/actions/Session.js
appium-inspector opens a url after starting a new session if it was in WebView. Current path is 404 since today, so lets change the path to the top.
> chore: tweak the initial page

- app/renderer/actions/Session.js
- app/renderer/components/Session/FormattedCaps.js
- app/renderer/components/Session/SavedSessions.js
- app/renderer/components/Session/Session.css
- app/renderer/components/Session/Session.js
- app/renderer/reducers/Session.js
This PR adds the ability to rename any saved capability set, through a new edit button next to the title.
Why is this useful? I have had situations where I need to replace one of my test phones, for which I had saved multiple capability sets. In order to update the caps and the set names, previously I would need to create entirely new sets, and delete the old ones. With this change, I only need to edit caps for the device udid/name, and rename the set title.
The implementation is fairly similar to that of editing the saved capabilities themselves. One key difference is that the new title is saved immediately after pressing the small save button - the Save button in the footer is not used.
Here is a brief video to show how this works: …
> feat: support renaming saved capability sets

- .github/workflows/node.build.yml
- .github/workflows/pr-validation.yml
This PR ensures that CI runs for Node 14 use NPM 8 instead of the default NPM 6. This is because NPM 6 does not auto-install peer dependencies, which are used in newer `@appium/fake-driver` versions.
I used `npm@8` instead of `npm@latest` to prevent any breaking changes in the future.
Worth noting that [Node 14 support ends on 2023-04-30](https://github.com/nodejs/release#release-schedule), so maybe it's simpler to just wait a few days and then remove it from CI entirely? 🤔 
Also, this is a good place to ask, perhaps it's worth removing the `on: pull_request` trigger in `node.build.yml`? That workflow is already fully covered by the PR validation workflow.
> ci: cleanup validation workflow

- ci-jobs/crowdin-sync-translations.js
- ci-jobs/crowdin-update-resources.js
- package-lock.json
- package.json
- test/e2e/inspector-e2e.test.js
- test/e2e/pre-e2e.test.js
- test/integration/client-actions.integration-test.js
This PR updates @appium/fake-driver to ~5.2.2~ 5.2.3.
A few notes:
1. It seems that `@appium/fake-driver` has dropped support for Appium 1.x. Since Appium Inspector only uses this package as a dev dependency, this will not affect regular users. However, **integration tests will now only run on Appium 2**.
2.  While investigating the integration tests, I noticed that `web2driver` is still setting the default path to `/wd/hub`. I've changed the path here, but perhaps this is something worth updating [at the source](https://github.com/headspinio/web2driver/blob/master/src/driver.js)?
3. ~Imports for `appium-support` were changed to `@appium/support`, except for one file in [appium-gui-libs](https://github.com/appium/appium-gui-libs/blob/5239eebaf0eab9078d9a0c50787bde30ecaf2c81/crowdin-sync-tr …
> chore(deps): update @appium/fake-driver to 5.2.3

- app/renderer/components/Session/Session.js
This is a small fix to disable the capability set Save/Save As buttons while the raw caps editor is enabled.
Should prevent situations like #628.
> fix: disable Save/Save As while raw caps editor is enabled

- app/renderer/components/Inspector/shared.js
This PR adds the class name locator strategy in the 'Find By' table when selecting elements with unique class names.
Considering that this strategy is listed as the fastest for both [iOS](https://github.com/facebookarchive/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance#select-the-most-effective-lookup-strategy) and [Android](https://github.com/appium/appium-uiautomator2-driver#element-location), I think it is worth adding.
Android uses the `class` element property, whereas iOS uses `type`.
Example:
> feat: add class name locator strategy where applicable

- app/renderer/components/Inspector/DeviceActions.js
- app/renderer/components/Inspector/SiriCommandModal.js
Small fixes for the recently added device action buttons:
* uses ButtonGroup for proper spacing between buttons
* replace deprecated Modal 'visible' method with 'open'
> fix: device actions fixes

- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Inspector/Inspector.js
- app/renderer/components/Inspector/SelectedElement.js
- app/renderer/reducers/Inspector.js
- assets/locales/en/translation.json
This PR aims to fix #353 and add a few more usability improvements along the way:
* Action buttons are no longer disabled if the element could not be found. Instead, they are disabled during the initial element search (starting from selecting an element, until its ID is (not) retrieved), to prevent an invalid state. As before, the buttons also remain disabled while timing search is ongoing.
* Adjust the text and positioning of the info alert about element not being interactable
* During timing search, show spinner only over the locator strategies table, instead of the whole application window
> fix: improve selected element actions

- app/renderer/routes.js
Small change needed for the eventual update to react-router v6. This updates the style of route initialisation to the one introduced in react-router 5.1, [as described here](https://github.com/remix-run/react-router/blob/main/docs/upgrading/v5.md#upgrade-to-react-router-v51).
> chore: update route initialisation style

- app/renderer/actions/Inspector.js
- app/renderer/components/Inspector/DeviceActions.js
- app/renderer/components/Inspector/ElementLocator.js
- app/renderer/components/Inspector/GestureEditor.js
- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Inspector/LocatedElements.js
- app/renderer/components/Inspector/LocatorTestModal.js
- app/renderer/components/Inspector/SelectedElement.js
- assets/locales/en/translation.json
This PR provides various visual improvements to the find element modal:
* Replace locator strategy dropdown with radio buttons (one less click and no scroll)
* Hide locator strategies that are unavailable for current `automationType`
* Render results count using antd Badge
* Render results list with responsive height (1-6 rows)
* Replace text for found element action buttons with icons + tooltip
* Add a clear button to selector and send keys input fields if text is entered
Here is a demonstration of the new behavior:
https://github.com/appium/appium-inspector/assets/37242620/3c553e19-bb62-4535-a95a-d4a63377f70f
> style: enhance find element modal

- app/renderer/components/Inspector/LocatedElements.js
This fixes the issue where, when searching for elements and selecting any result from the list, if the same result was then selected again, the highlight calculation would be requested again.
> fix: do not resend highlight for selected element

- babel.config.js
- package-lock.json
- package.json
Resolves linting errors in #846.
Technically the updated plugin was already included as part of `@babel/preset-env` (as there are no additions in `package-lock.json` here), but #846 results in it being replaced with `@babel/plugin-transform-class-properties`, which then causes the lint issue. So for now, until we dig deeper into the cause of the linting error, it is being explicitly imported.
> chore(deps): update babel class properties plugin

- app/renderer/actions/Inspector.js
- app/renderer/components/Inspector/LocatedElements.js
- app/renderer/lib/appium-client.js
- app/renderer/reducers/Inspector.js
This PR implements #698.
When searching for an element, the results screen will now also show the elapsed time (arrow not included):
> feat: show search time in locator search results

- app/renderer/components/Inspector/LocatedElements.js
- assets/locales/en/translation.json
This PR removes the Copy ID button from the locator search results.
As of #842, the found element IDs are presented in a list, rather than a dropdown, which means that it is now possible to directly select the text inside a list item, eliminating the need for a dedicated button.
> fix: remove copy id button

- .eslintrc.json
- app/renderer/.eslintrc
- app/renderer/.eslintrc.json
- package-lock.json
- package.json
This PR replaces the old `eslint-config-appium` module with the new `@appium/eslint-config-appium` module. 
Most rules appear to be the same, with the exception of the removed indentation rule - it has been explicitly added back.
Additionally, `.eslintrc` files have been renamed to `.eslintrc.json` to [match the supported formats](https://eslint.org/docs/latest/use/configure/configuration-files#configuration-file-formats).
> chore(deps): migrate to new eslint-config-appium module

- app/renderer/components/Inspector/HighlighterRects.js
- app/renderer/components/Inspector/LocatedElements.js
- app/renderer/components/Inspector/Screenshot.js
- app/renderer/components/Inspector/SelectedElement.js
`this.setState` does not overwrite the parameters that are not specified, so they can be omitted from the method call. This approach is already used in most other calls of `this.setState`.
> chore: remove unneeded params in this.setState

- app/renderer/index.js
- app/renderer/polyfills/browser.js
- app/renderer/store/configureStore.development.js
- app/renderer/store/configureStore.js
A few ESLint ignore flags can be removed. The `global-require` flag has been deprecated since ESLint 7, and the others do not result in any warnings upon their removal.
> chore: remove unused/deprecated eslint ignore flags

- package-lock.json
- package.json
This PR removes the `source-map-support` dependency. It's not directly used anywhere, and is already integrated in Node 12.12+ if necessary. Browser and desktop versions work just fine without it.
> chore(deps): remove source-map-support

- app/renderer/index.js
This enables the new [React 18 root API](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis), removing the warning that always appears on launch.
However, this does add a new warning when hot module replacement is activated. It can be removed by migrating to React Fast Refresh, but that in turn requires rewriting the app to use React function components, as well as Parcel 2.
> chore: switch to React 18 root API

- renovate.json
This configures Renovate to automatically add the `dependencies` label for any of its version update PRs.
> chore: autoadd dependencies label to renovate PRs

- app/renderer/components/Inspector/Inspector.js
- app/renderer/components/Inspector/Screenshot.js
- app/renderer/components/Inspector/Source.js
This PR implements #504, similarly to #635.
In addition, the Pause/Start Refreshing Source button in the header is now hidden when not using MJPEG mode, since all it does is enter a state where neither screenshot nor source are changing. The button still remains functional in MJPEG mode.
> fix: show spinner over source in MJPEG mode + hide pause/start refresh button when not in MJPEG

- app/renderer/components/Inspector/LocatedElements.js
- assets/locales/en/translation.json
This PR is a highly specific change, but bear with me.
Background: Up until a week ago I was unaware of the `appium:disableIdLocatorAutocompletion` capability. I had been testing an Android app that had Jetpack Compose elements with `testTag`s, and I was wondering why they were listed as `resource-id`s, yet I could not find them through the element search. I didn't delve too deep into this, and just settled on using simple XPaths. Fast forward to this week, and the aforementioned capability has now unlocked the ability to find these elements by id.
To avoid others getting into the above situation, I am suggesting to add an infobox that will appear under very specific circumstances:
* `UiAutomator2` driver is used
* Element search is done using the `id` locator strategy
* The selector used …
> feat: add infobox for disabling package name autocompletion of id locators

- app/renderer/components/Inspector/ElementLocator.js
- app/renderer/components/Inspector/Inspector.css
- assets/locales/en/translation.json
This PR should only affect Appium 1.x users.
It fixes an application error if element search is opened in a session with `appium:automationName` not specified. Only the default locator strategies will be shown in that case.
In order to help users unhide any platform-specific capabilities, I have added a new infobox that only appears if `appium:automationName` is missing:
> feat: fix element search error + add infobox if automationName is missing

- README.md
- app/main/windows.js
- app/renderer/components/Inspector/Inspector.js
- app/renderer/components/Session/AdvancedServerParams.js
- app/renderer/components/Session/Session.css
- app/renderer/stylesheets/app.global.less
This PR adjusts the default and minimum dimensions for the main window and several components.
The original goal was to try and reduce these dimensions in order to assist with issues like #549, but testing on Windows showed that the minimum height actually needs to be slightly _increased_ to adjust for the title bar (which is likely to affect Linux the same way). The minimum width could still be decreased, and as a result, the new minimum dimensions have been changed to `890 x 710`.
Other notable adjustments:
* Set default window height to match minimum height (may further help with the issue linked above)
* Adjust minimum sizes for a few components (app body, capabilities table, inspector) to fix their appearance at minimum window size
* Slightly increase available width of elements in …
> fix: adjust window dimensions and appearance at min window size

- app/renderer/components/Session/AdvancedServerParams.js
- app/renderer/components/Session/AttachToSession.js
- app/renderer/components/Session/CapabilityControl.js
- app/renderer/components/Session/CapabilityEditor.js
- app/renderer/components/Session/CloudProviderSelector.js
- app/renderer/components/Session/FormattedCaps.js
- app/renderer/components/Session/SavedSessions.js
- app/renderer/components/Session/ServerTabBitbar.js
- app/renderer/components/Session/ServerTabBrowserstack.js
- app/renderer/components/Session/ServerTabCustom.js
- app/renderer/components/Session/ServerTabExperitest.js
- app/renderer/components/Session/ServerTabHeadspin.js
- app/renderer/components/Session/ServerTabKobiton.js
- app/renderer/components/Session/ServerTabLambdatest.js
- app/renderer/components/Session/ServerTabPcloudy.js
- app/renderer/components/Session/ServerTabPerfecto.js
- app/renderer/components/Session/ServerTabRemoteTestKit.js
- app/renderer/components/Session/ServerTabRobotQA.js
- app/renderer/components/Session/ServerTabSauce.js
- app/renderer/components/Session/ServerTabTestingbot.js
- app/renderer/components/Session/Session.js
This PR is a partial implementation of #879, covering all the components in the Session route.
Most of the components were relatively straightforward to migrate: only 2 needed lifecycle methods, and only 1 needed an instance variable. Though I have a hunch that the Inspector route will be more complicated...
I've also removed a few unnecessary/unused methods:
* `componentDidMount` in `CloudProviderSelector` - needlessly duplicates some calls in the equivalent `Session` method
* `handleCloseModal` in `CloudProviderSelector` - `<Modal onCancel=` already handles this case
* `removeCloudProvider` in `Session` - unused and already handled in `CloudProviderSelector`
> chore: migrate Session items to React function components

- app/renderer/components/ErrorBoundary/ErrorMessage.css
- app/renderer/components/ErrorBoundary/ErrorMessage.js
Two small fixes for the refreshed error message:
1) The GitHub link, when clicked in the desktop app, would open in the app itself. All other links open in a new browser tab, so this one was also adjusted accordingly.
2) The copy trace button may overlap the error title, if it is too long. To avoid this, it has been moved to the left side, below the error icon, and vertically closer to the trace text.
> fix: open errormessage link in browser + move copy button to left side

- app/renderer/components/Session/CapabilityControl.js
This fixes 2 things for the filepath capability in the capability editor:
1) It is now possible to manually type a string in the value field. Until now, it was only possible to use the open file button.
2) The extension filter for `.appiumsession` files has been removed. There are many reasons to use other extensions here, such as for the `appium:app` capability.
> fix: enable manual text input for filepath capability + remove filtering by extension

- app/renderer/actions/Inspector.js
This fixes a problem where it was not possible to save new gestures. The fix implementation is taken from the code for saving new sessions.
Not actually sure when this issue was introduced, since I already had several saved gestures from an older version.
> fix: resolve issue with saving gestures

- app/renderer/components/Inspector/Source.js
This fixes an issue where the placeholder text for loading source ("Gathering initial app source...") was not shown. It was therefore likely to affect the source error text too.
It seems this is caused by some interaction with the antd Spin component, where text after it is not shown. Moving text before the Spin makes it show up as expected.
> fix: resolve issue where source loading/error text was not shown

- app/renderer/actions/Inspector.js
When selecting an element via the highlighted rectangle overlaid over the screenshot, oftentimes there may be an issue where the selected element actions load endlessly, meaning, the element search did not finish.
This was caused by a state mutation of the expanded paths array. By copying this array, the issue is resolved.
> fix: resolve issue with loading selected element

- package.json
Adds one missing `cross-env` call. I was confused why I wasn't able to build the browser version on my Windows machine.
> chore: add missing cross-env invoke

- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Session/Session.css
I opened the browser build in Firefox and was wondering why I was seeing scrollbars all over the place. Realised that `-webkit-scrollbar` doesn't apply to non-WebKit environments - who would have thought.
So here I've added a fix that _is only supported_ in Firefox. ([at least for now](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width#browser_compatibility))
> fix: hide ugly scrollbars in Firefox

- app/renderer/components/Inspector/Commands.js
- app/renderer/components/Inspector/ElementLocator.js
- app/renderer/components/Inspector/HeaderButtons.js
- app/renderer/components/Inspector/HighlighterCentroid.js
- app/renderer/components/Inspector/HighlighterRect.js
- app/renderer/components/Inspector/HighlighterRects.js
- app/renderer/components/Inspector/LocatedElements.js
- app/renderer/components/Inspector/LocatorTestModal.js
- app/renderer/components/Inspector/RecordedActions.js
- app/renderer/components/Inspector/SavedGestures.js
- app/renderer/components/Inspector/Screenshot.js
- app/renderer/components/Inspector/SelectedElement.js
- app/renderer/components/Inspector/SessionCodeBox.js
- app/renderer/components/Inspector/SessionInfo.js
- app/renderer/components/Inspector/SiriCommandModal.js
- app/renderer/components/Inspector/Source.js
- app/renderer/reducers/Inspector.js
This PR continues the implementation of #879, covering almost all the components in the Session route. The two exceptions being `GestureEditor` and `Inspector`, which are the most complex components, so I thought it best to leave them for a separate PR.
As I expected, this was overall more complicated than Session, with more uses of React hooks. Like with Session, a few cleanups were also done here, mainly in `ElementLocator`, `LocatedElements`, and `HighlighterRects`.
Each individual component was tested to load and execute its main functionality.
> chore: migrate most Inspector items to React function components

- app/renderer/components/Inspector/SavedGestures.js
- app/renderer/components/Inspector/Screenshot.js
Two small fixes for the saved gesture usage scenario:
* Use `Button.Group` for the saved gesture actions buttons (looks nicer)
* Add missing key for the drawn gesture points (otherwise React throws a warning)
> fix: group gesture action buttons + add missing key for drawn gesture points

- app/renderer/actions/Inspector.js
- app/renderer/components/Inspector/Inspector.js
- app/renderer/reducers/Inspector.js
This PR fixes issues with the session expiry prompt and timeouts, which could have caused repeated 'Session closed' errors to be shown after the session had already been closed.
The timeout functionality that handles the expiry of this inactivity prompt has also been moved directly to the Inspector component. This is done in preparation for #882.
> fix: do not repeat notification about session closed due to inactivity

- package-lock.json
This PR rebuilds the `package-lock.json` file, as a result of running `npm run clean:npm` (which deletes `package-lock.json`, `node_modules`, and then runs `npm install`).
All unpinned dependencies have therefore been updated, which also reduced a few vulnerabilities.
Both the Mac app and browser version have been confirmed to still work.
> chore(deps): rebuild package-lock

- app/renderer/components/Inspector/HighlighterRects.js
Quick PR to add a `key` property that React was complaining about.
This key is for a highlighter shown when selecting a found element, so its only properties are its dimensions, and the key must be assembled from all of them in order to be uniquely rendered.
> chore: fix missing highlighter key

- package-lock.json
- package.json
This PR removes the `release` module. The module has not been updated in a while, and we also do not use it, since releases are created using another approach. This change also further reduces the vulnerability count.
> chore(deps): remove release module

- app/renderer/components/Inspector/Inspector.js
This fixes a problem I've mainly noticed when working with an app in landscape orientation.
When opening such an app with the default inspector app window dimensions, the screenshot width is around 450 pixels. However, if I refresh the source, the screenshot width slightly increases, and continues increasing until it reaches the max limit of 500 pixels:
https://github.com/appium/appium-inspector/assets/37242620/f95dafba-0445-406d-9064-75861616a0ac
Now, the default screenshot width is a bit smaller at 430 pixels, but it no longer changes upon source refresh:
https://github.com/appium/appium-inspector/assets/37242620/9ef0b346-7013-40b2-bbeb-e4296fd31bde
Of course, the screenshot size can still be adjusted by changing the app window size.
> fix: resolve issue with unwanted incremental scaling in landscape

- app/renderer/components/Inspector/Inspector.js
- app/renderer/components/Session/Session.js
- app/renderer/routes.js
- package-lock.json
- package.json
This PR updates `react-router` from v5 to v6 and therefore resolves #883.
This migration was a lot simpler than I anticipated. The only caveat here was that routes are now relative by default, so both of the route change instances now explicitly replace the history stack, rather than push a new entry onto it.
Changes have been tested in the Mac app and Chrome version, including via `initFromQueryString`.
> chore(deps): upgrade to `react-router` v6

- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Inspector/Inspector.js
This PR slightly adjusts the placement of element highlighters over the app screenshot:
* Remove the border around the app screenshot - highlighters were taking it into account
* Do not truncate the image width when calculating the scale ratio (use `width` instead of `offsetWidth`)
* Since this width was already retrieved in the parent method, it is now being passed as a parameter, which allows to remove one `querySelector` request
> fix: slightly adjust element highlighter placement

- app/renderer/lib/appium-client.js
This PR improves the screen size calculation specifically when using UiAutomator2, either in landscape mode, or when changing device orientation in any way. It also fixes #665 and fixes #701.
The core issue was caused by the window width and height being effectively hardcoded to portrait mode.
The fix reuses the existing `driver.getWindowRect` call to check the current dimensions (which may be smaller than the full screen size, due to UiAutomator2 calculations that I will discuss in a separate issue). The dimensions are then used only to determine the screen orientation, and the actual values are still taken from the full screen size, as before. This means that portrait mode behavior is entirely unchanged.
Due to the aforementioned UiAutomator2 calculations, as well as some webview …
> fix: improve screen size calculation for Android landscape mode & when changing orientation

- app/renderer/components/Inspector/HighlighterRects.js
Caught this bug by accident. It could cause React to throw a warning about duplicate keys, and render an expand centroid at the screenshot's top left corner, which would remain visible even after hiding centroids, likely until the session would be closed.
The problem was caused by a possible overlap between element highlighter keys and centroid keys.
Element highlighter keys are their index in the source tree, separated by dots, meaning the first child of the root would have the key `0.0`.
Centroid keys are their coordinates, but also separated by a dot, so a centroid at (x:0, y:0) would also have the key `0.0`.
The issue was resolved by using a comma when creating the centroid key.
> fix: resolve issue with leftover expand centroid

- app/renderer/lib/appium-client.js
- app/renderer/lib/webview-helpers.js
This PR improves calculations for generating element highlighters when inspecting a webview. Both iOS and Android had issues in such situations.
Note that highlighter generation in native context is not affected.
Here the problem was fairly simple - the top offset from the Chrome address bar was being ignored:
The issue was fixed by finding the actual webview element (`android.webkit.WebView`), which had correct dimensions, and using its X and Y coordinates as the starting points:
This also allowed to fix a problem in landscape mode, where the X axis would also need an offset if the device had a hole punch camera or a similar hardware configuration, resulting in the webpage not extending to that area.
The solution was also confirmed to work when the Chrome address bar was scrolled out of …
> fix: improve highlighter positions in webview

- app/renderer/components/Inspector/Commands.js
This PR fixes a problem where some commands in the Commands panel could not be executed (specifically, `rotateDevice`, `setGeoLocation`, `executeScript` and `updateSettings`).
The issue was caused by a state mutation, so the fix involved simply cloning the affected `args` array before mutating it.
Note that `_.cloneDeep` was used instead of the more performant spread syntax, since the `args` array may have multiple levels (e.g. for XCUITest driver's `mobile: pushNotification`)
> fix: resolve issue with some commands not working

- app/renderer/components/Inspector/Inspector.js
- assets/locales/en/translation.json
This PR adds a new button that allows to save the full-size version of the currently shown application screenshot:
It is one of those features that initially didn't even occur to me, but once it did, I realised it could be extremely useful.
Note that the button is not shown in MJPEG mode.
> feat: add button to save current application screenshot

- app/renderer/actions/Session.js
- app/renderer/components/Session/Session.js
This PR resolves #1026. The inspector screen should no longer open if session creation fails for any reason.
> fix: do not open inspector screen if session creation fails

- app/renderer/actions/Session.js
Changes remote path for Appium 2x. "/wd/hub" removed.
> fix: update robotqa session path for Appium 2

- app/renderer/components/Inspector/Source.js
- app/renderer/util.js
- test/unit/util-specs.js
- Add some attributes that we should consider for uniqueness
- Add search for attributes that might be unique as pairs
- Show a few more attributes by default in the XML source
> feat: improve xpath locator suggestions

- app/renderer/components/Inspector/Source.js
- app/renderer/util.js
- test/unit/util-specs.js
I realized there are actually two categories of 'unique' attributes when constructing a selector.
- intentionally unique / static (things like 'id' or 'content-desc' which the developer sets ideally in a way which is unique and doesn't change from run to run. this doesn't mean they are actually always unique. but from the perspective of selector generation, if we find a unique 'id' attribute on an element, then this is sufficient for us to consider the selector unique enough)
- accidentally unique / dynamic (things like 'text' or 'label' which might contain e.g. user generated content or other strings. the fact that they are unique in the xml document is not necessarily a good predictor that they will be unique on subsequent runs of the app.)
This change refactors the selector generation …
> fix: update xpath selector selection logic

- app/renderer/util.js
- test/unit/util-specs.js
this PR primarily  removes class/type from xpath uniqueness attributes. instead adds logic to look for unique node names and refer to those if necessary (since class/type are always the same as node names)
> fix: update xpath selector selection logic yet again

- app/renderer/lib/client-frameworks/python.js
This adds recorder support for Appium Python client v3 and closes #1145.
* Change capabilities parsing to options style
* Remove unsupported methods (`launch_app`, `close_app`, `reset`)
> feat: add recorder support for Python client v3

- app/renderer/lib/client-frameworks/java.js
- app/renderer/lib/client-frameworks/js-oxygen.js
- app/renderer/lib/client-frameworks/js-wd.js
- app/renderer/lib/client-frameworks/js-wdio.js
- app/renderer/lib/client-frameworks/python.js
- app/renderer/lib/client-frameworks/robot.js
- app/renderer/lib/client-frameworks/ruby.js
As same as https://github.com/appium/appium-inspector/pull/1147, we can remove launchApp/closeApp/reset commands from template since these commands no longer exists in this inspector library
> chore: remove unused template commands

- app/renderer/components/Inspector/Commands.js
- assets/locales/en/translation.json
Currently, when attempting to call the `executeScript` or `updateSettings` command, if an invalid JSON argument is given, the app will return 2 errors - one for the invalid JSON, and another for the actual method execution.
Changes included in this PR:
* do not call the client method if JSON parsing fails
* add translation key for the JSON error, which also adds the failed JSON string inside the error
> fix: improve error for invalid JSON in command argument

- app/renderer/components/Inspector/Commands.js
This PR relaxes the valid syntax for the `executeScript` command argument.
Currently, the input argument must be an array, which is not obvious - only the WDIO client requires this syntax; all other clients accept a dictionary or map.
With this change, the array brackets are made optional.
> fix: use relaxed syntax for `executeScript` argument

- app/renderer/lib/appium-client.js
This PR fixes an issue where element highlighters for Android tablets were being drawn incorrectly.
The core issue stems from the `deviceScreenSize` parameters, which appear to match portrait mode for phones, but landscape mode for tablets. This has now been adjusted for.
Resolves #1154.
> fix: adjust highlighters for Android tablets

- app/renderer/lib/client-frameworks/java.js
This PR fixes the Java recorder syntax for `executeScript`, where `Map.ofEntries` was incorrectly called with the parameter syntax of `Map.of`. Now the parameters are being passed correctly.
It is important to use `Map.ofEntries`, because `Map.of` is limited to 10 key-value pairs, and some extension methods support more than 10 parameters.
> fix: update Java recorder syntax for executeScript

- app/renderer/lib/appium-client.js
Followup to #1162, the condition is adjusted to (hopefully) make it more readable.
> fix: adjust logic for Android highlighters

- app/renderer/lib/client-frameworks/framework.js
- app/renderer/lib/client-frameworks/java.js
- app/renderer/lib/client-frameworks/js-oxygen.js
- app/renderer/lib/client-frameworks/js-wdio.js
- app/renderer/lib/client-frameworks/python.js
- app/renderer/lib/client-frameworks/robot.js
- app/renderer/lib/client-frameworks/ruby.js
While working on recorder updates for Python, I made various changes that affect all recorder frameworks, so I decided to submit them as a separate PR.
Changes include:
* Fix `codeFor_executeScript` for Java (wrong expected format for the argument variable)
* Move `codeFor_startActivity` to the base class since it will be the same for all frameworks
* Split `codeFor_executeScript` into handler methods with argument and without arguments. Move common method to the base class since it will be the same for all frameworks
* Remove various base class methods that are unused or already implemented in all recorder frameworks
* When encountering an unsupported locator strategy or method, do not raise error, but instead add a comment in the generated code
* There is one situation where an error …
> fix: adjustments for shared recorder framework code

- app/renderer/lib/client-frameworks/python.js
This PR updates the recorder-generated code for the Python client:
* Add missing driver commands (`activateApp`, `terminateApp`, `sendSMS`)
* Fix `executeScript` implementation
* Apply conversion to Python values also for parameters inside arrays and objects
* Reorder and group driver command implementations
* Improve formatting for generated code (remove semicolons, add variable assignment where needed)
> feat: update Python recorder code

- app/renderer/lib/client-frameworks/ruby.js
This PR updates the recorder-generated code for the Ruby lib core client.
* Fix `uiautomator` locator strategy
* Do not add quotes around dictionary keys
* Fix `executeScript`
* Add `activateApp` and `terminateApp`
* Change many methods deprecated in `ruby_lib_core` 7.3 to their mobile extension equivalents
* Certain mobile extensions like `mobile: setConnectivity` first require UI changes
* Reorder and group driver command implementations
> feat: update Ruby recorder code

- app/renderer/lib/client-frameworks/js-wdio.js
This PR updates the recorder-generated code for the WDIO client.
* Change boilerplate import to ESM
* Always pass locator strategy to element lookup ([reference](https://github.com/webdriverio/webdriverio/blob/v7/packages/webdriverio/tests/findStrategy.test.ts#L310))
* Fix `executeScript` and `updateSettings`
* Add `activateApp` and `terminateApp`
* Change many methods deprecated in `ruby_lib_core` 7.3 to their mobile extension equivalents
* Reorder and group driver command implementations
> feat: update WDIO recorder code

- app/renderer/lib/client-frameworks/index.js
- app/renderer/lib/client-frameworks/java-common.js
- app/renderer/lib/client-frameworks/java-junit4.js
- app/renderer/lib/client-frameworks/java-junit5.js
This PR adds a new recorder for Java JUnit 5. The only difference from JUnit 4 is some imports and annotations, so most of the code generation is shared between both classes, and each class only implements its own boilerplate method.
Resolves #156.
> feat: add Java JUnit 5 recorder

- app/renderer/lib/client-frameworks/js-oxygen.js
This PR updates the recorder-generated code for the Oxygen HQ client. Similarly to Robot, I'm not sure how well maintained this client is, but this should be an improvement nonetheless.
* Simplify module detection (`win` or `mob`)
* Rely on WDIO for locator strategy identification
* Fix `executeScript` and `updateSettings`
* Add `activateApp`, `terminateApp`, various web and context methods
* Change many methods deprecated in `ruby_lib_core` 7.3 to their mobile extension equivalents
* Reorder and group driver command implementations
> feat: update Oxygen recorder code

- app/renderer/lib/client-frameworks/dotnet-nunit.js
- app/renderer/lib/client-frameworks/index.js
This PR adds a new recorder for .NET NUnit.
Resolves #804.
> feat: add .NET NUnit recorder

- package-lock.json
- package.json
This removes the `@types/react-router-dom` dev dependency.
`react-router-dom` ships its own types since v6, and the definitelytyped repo no longer stores them since April, so they are safe to remove.
> chore(deps): remove @types/react-router-dom

- app/renderer/actions/Session.js
- package-lock.json
- package.json
This PR replaces `ky` with `axios`. There's no need for two HTTP clients, and `ky` was outdated anyway.
Local session discovery was tested to still work.
> chore(deps): remove ky

- app/renderer/actions/Session.js
I saw "cannot read properties of undefined" error for `value` in current implementation. Maybe `(await axios(detailsUrl).data)` result was undefined then. Lets wait the axios response, then check the data and value. This fixed my observed issue
> fix: undefined value reference

- README.md
- test/unit/webview-helpers-specs.js
1. Better use `npm ci` than `npm install`, to fully rely on `package-lock.json` and not possibly modify it unintentionally
1. Add note about `node-gyp` required installs for python and c/c++ compiler tools
1. Running `webview-helpers-specs.js` only in my IDE resulted in
```
TypeError: Cannot read properties of undefined (reading 'eql')
```
And I found that it is the only spec that calls `chai.use(chaiAsPromised);` but not `chai.should();`.
> Update dev install doc and single test run

- app/renderer/components/Session/Session.css
The existing style is mostly [antd](https://github.com/ant-design/ant-design/tree/4.24.15) default blue, and custom sets `anticon` `:hover` to be like red.
But in most buttons with icon only a reduced part is colored like this ; this change ~makes it be applied to the whole button~ removes this custom style.
~Looking at [antd mixins for buttons](https://github.com/ant-design/ant-design/blob/4.24.15/components/button/style/mixin.less#L14), I deal with the same pseudo-classes (`:hover`, `:focus`, and `:active`), and then I set the same 3 style properties (`color`, `border-color`, and `background`).~
And this keeps the default style when the button is `disabled`.
Some not directly targeted elements were previously having the custom `:hover` style too, like some arrows for toggle blocks or …
> style: remove custom anticon :hover style

- renovate.json
Since `ky` is no longer being used, its specific Renovate configuration can also be removed.
> chore(renovate): remove obsolete ky config

- app/renderer/lib/appium-client.js
Simple fix for highlighter generation. I had somehow missed that the `deviceScreenSize` values are strings, not integers, whose comparison works differently... (`'1280' > '800' -> false`)
Fixes #1154 (hopefully)
> fix: adjust highlighter positions again

- package.json
Azure Pipelines were seemingly failing to build Windows artifacts because 7zip had 2 processes writing to the same file. This gives each process a different file to write to.
I tested this locally and the issue was gone.
> fix(build): fix race condition for Windows artifacts

- app/renderer/components/Session/Session.js
I found `start session` would throw error `Invariant failed: A state mutation was detected between dispatches, in the path 'session.caps.0.name'.  This may cause incorrect behavior.` first time. function `loadNewSession` use caps directly would cause this bug.
This pr will fix this bug by `cloneDeep(caps)`
> fix: resolve issue with Start Session sometimes needing a second click

- app/renderer/actions/Session.js
- app/renderer/lib/appium-client.js
W3C WebDriver spec does not support `getSession` endpoint call. chrome session with w3c mode returned 404 for the endpoint recently, then `this.driver.getSession` got 404.
Newer drivers do not need to got to fallback, which needs to call getSession, so lets minimize the endpoint call in `appium-client.js`.
In Session.js, it has a case that MJSONWP mode returns `platform` instead of `platformName` in chrome.
e.g, with:
```
"appium:chromeOptions": {
"w3c": false
}
```
then, `attachedSessionCaps.platformName` returns `null` but `attachedSessionCaps.platform` has expected value. So lets get the platformName with `attachedSessionCaps.platformName || attachedSessionCaps.platform`
> fix: reduce getSession endpoint calls in hybrid mode

- .github/workflows/crowdin-update-resources.yml
Currently Crowdin resource update runs for every commit on main, even if no relevant changes exist. Now it will only run for changes in the translation file, and the workflow file.
> chore: only run Crowdin update if changes exist

- app/renderer/components/Session/Session.js
- assets/locales/en/translation.json
This renames the 'Desired Capabiities' tab in the session builder to 'Capability Builder', which is already used in the docs.
> fix: rename Desired Capabilities to Capability Builder

- .github/labeler.yml
- .github/workflows/auto-labeler.yml
Adds an auto-labeler action for PRs, same as in the main Appium repo.
The `dependencies` label is still configured in `renovate.json` (although it may also be worth moving that here for a single source of truth)
> chore: add auto-labeler for PRs

- .github/labeler.yml
- renovate.json
This adds the dependencies label config in the labeler, for cases where dependencies are changed by someone other than Renovate.
Renovate's own configured labeling is intentionally kept, since it also covers things like GitHub Actions, which are harder to track with the labeler.
> chore: add dependencies label in labeler

- .github/labeler.yml
* remove `sync: true` option since it will just remove manually added labels upon new commits
* also add documentation label for changes to README or /docs files
> chore: update PR auto-labeler

- .github/workflows/crowdin-sync-translations.yml
Not sure why auto-labeler doesn't apply to the Crowdin sync PR, but thankfully the sync job also allows specifying the label.
> chore: add i18n label for Crowdin sync

- app/renderer/lib/appium-client.js
- app/renderer/lib/webview-helpers.js
This PR fixes two things:
1. On iOS, webviews that didn't occupy the full screen (as in Safari) were not previously considered.
2. On both platforms, `window.scrollX` and `window.scrollY` were also not considered, which are necessary when thinking about the positions of web elements on the screen (web element position is absolute, not viewport relative as mobile elements are).
> fix: correctly account for position and scroll values of webviews

- app/renderer/components/Inspector/SelectedElement.js
- app/renderer/reducers/Inspector.js
Quick fix for how the Element ID property is displayed in the Selected Element panel. Currently, the property value field starts empty, and is only populated once the element is found. Without a spinner it may be unclear that Appium is searching for the element in the background.
This also fixes the problem when, if an element is selected, and then a different one is selected (without unselecting the current one), the element ID value field keeps the ID of the previous element, until the new one is found. Now it is properly cleared first.
> fix: show spinner for element ID property until it is retrieved

- app/renderer/actions/Session.js
Small fix for the cloud provider selection modal for the following user flow:
1. Open the cloud provider selection and enable one or more providers
1. Close the selection and switch to any provider tab
1. Open the cloud provider selection again and disable the currently selected provider
Currently this behavior results in the server details disappearing altogether, though it can be fixed by explicitly selecting the default server tab.
This change makes it so that the app automatically switches to the default tab in this situation.
> fix: fallback to default server tab when unselecting current provider

- app/renderer/actions/Inspector.js
- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Inspector/SelectedElement.js
- app/renderer/utils/locator-generation.js
- app/renderer/utils/source-parsing.js
- test/unit/utils-locator-generation-specs.js
This PR adds generation of suggested selectors for the UiAutomator locator strategy, when using the UiAutomator2 driver.
While it does not cover the full breadth of capabilities for this strategy (e.g. no UiScrollable or child selectors), it can still assemble selectors out of 4 attributes (`resource-id`, `text`, `content-desc`, `class`), and add indices, which should cover most use cases.
It is also oftentimes faster than the `id` strategy... 👀 
⚠️ Important to note that this strategy seems to only find elements _in the last direct child of the hierarchy_ - elements under any other direct child are not visible. I assume this is some sort of limitation (whether intentional or not) from Google's end. This is why the implementation requires recalculating the full DOM Document, the DOM node, …
> feat: add suggested selector for UiAutomator strategy

- app/renderer/actions/Session.js
- app/renderer/components/Session/ServerTabTestingbot.js
This PR renames the TestingBot `key` and `secret` params to `username` and `accessKey`.
The reason for this change is because `getRunningSessions` checks if both `username` and `accessKey` are set to determine if an `Authorization` header needs to be sent with the Axios GET request to `/sessions`.
https://github.com/appium/appium-inspector/blob/main/app/renderer/actions/Session.js#L935-L944
> fix: rename TestingBot key and secret to username and accessKey

- renovate.json
Minor adjustments to the Renovate config:
* Allow automerge for GH Action dependencies
* Prevent automerge for pre-release packages
* Disable major updates for several packages that require additional code changes. The goal is to eventually remove them from this list.
> chore: update Renovate config

- app/renderer/src/utils/other.js
Current implementation adds `appium:` for no-input field as well like below:
This change will not add `appium:` for undefined keys
> fix: do not add appium: for undefined

- app/renderer/src/actions/Session.js
- app/renderer/src/assets/locales/en/translation.json
- app/renderer/src/components/Session/CapabilityEditor.jsx
- app/renderer/src/components/Session/FormattedCaps.jsx
- app/renderer/src/components/Session/Session.module.css
- app/renderer/src/reducers/Session.js
Fix #1196
Added validations for duplicate capability set names upon saving.
1. In Save As modal
2. In Inline editor:
> fix: Add validation for duplicate capability name

- babel.config.js
- package-lock.json
- package.json
This replaces `@babel/plugin-proposal-class-properties` with `@babel/plugin-transform-class-properties`, since the former is deprecated. The latter is already imported as part of `@babel/preset-env`.
> chore(deps): replace babel proposal plugin with built-in version

- app/electron/main/main.js
Right now, building the dev version of the Electron app fails due to missing module `node:url`. This makes sense, since `node:` prefixes were only added in Node `14.18` (the app currently uses `14.16`).
The cause of this error is in `electron-extension-installer` -> `rimraf` -> `glob`, where this prefix was introduced in `10.3.13`.
I tried to add an override for `rimraf` to use `glob` `10.3.12`, however, this resulted in a similar error for `node:path` due to `path-scurry`, which in turn is a dependency of `glob`.
I suppose it's possible to add another override, but I think this is becoming a bit too hacky, so a simpler approach is to just uncomment uses of `electron-extension-installer` until we upgrade to Node `>=14.18`, that is, Electron `>=15`.
Closes #1511.
> chore: comment out dev extension install

- app/common/actions/Inspector.js
- app/common/actions/Session.js
- app/common/components/Session/CapabilityControl.jsx
- app/common/components/Session/Session.jsx
- app/common/lib/appium-client.js
- app/common/shared/polyfills.js
- app/common/utils/locator-generation.js
- app/common/utils/logger.js
- app/common/utils/other.js
- app/electron/renderer/polyfills.js
- app/web/polyfills.js
- package-lock.json
- package.json
- renovate.json
This PR adds a basic `Logger` class for abstracting away some logging implementations for better maintenance. The class itself still executes basic `console` calls under the hood, but this can be improved in the future.
The following logging implementations have been replaced with `Logger`:
* All uses of `console` in `common` files
* All uses of the `log` method imported from the shared `polyfills` file (there were only 2 such instances)
* The browser polyfill still used `console`, so there is no difference
* The Electron polyfill used `electron-log`, so this dependency has been removed
The actual main goal of this PR is to remove `electron-log`, as it is only being called in the renderer process anyway, and also it was causing issues for the Vite migration.
> chore: use common logger class

- app/common/lib/client-frameworks/js-wdio.js
The currently generated code for WDIO tap and swipe actions still relies on TouchActions, which were removed in WDIO v8. This PR updates the generated code to use the `action` command.
Since the command was only added in WDIO v8, all generated code now also required WDIO v8.
Related to #1538.
> fix: update WDIO generated code for tap/swipe actions

- app/web/polyfills.js
This adds the `fs` and `util` exports for web polyfills, which are already exported for Electron. While they are not actually used for web, Vite requires that they are exported properly.
> chore: add missing web polyfill exports

- app/common/store.js
- package-lock.json
- package.json
This changes the current conditional import for `redux-logger` to a top-level import. While the conditional import causes an error in Vite (`require is not defined`), it seems that it is not required in the first place, since the logging middleware initialisation is behind the development flag anyway. This behavior was confirmed in both dev and production Electron app versions.
Additionally, this PR adds the types for `redux-logger` for better DX.
> chore: move redux-logger import to top

- app/common/configs/i18next.common.js
- app/common/utils/other.js
This PR breaks up the `config` object defined in `i18next.common.js` due to the following reasons:
* The whole object is exported, but only the `namespace` property is used this way
* The `platform` property is never used, and breaks the Vite production build
* The `languages` property is only used once
* The `fallbackLng` property is used only once, but should be used twice, so it is extracted as a dedicated const
> chore: break up i18next config object

- app/common/components/Inspector/Inspector.jsx
This PR disables the ability to switch the Session Inspector tab until the screenshot has finished loading. It helps with situations where the screenshot takes a while to load, so the user may attempt to execute other Inspector actions, which may depend on the data retrieved alongside the screenshot (such as `windowSize`). Related to #1543.
It's likely that not all tabs actually depend on this data (such as Recorder), but for consistency it looks better if all of them are in the same state.
Functionality was tested to work fine in both normal and MJPEG modes.
> fix: disable Inspector tabs until screenshot has loaded

- app/electron/main/helpers.js
- app/electron/main/main.js
- app/electron/main/menus.js
- app/electron/main/windows.js
A few more relatively minor changes to prepare for Vite:
* Move the defined window URL paths from `main.js` to `windows.js` since they are not used anywhere else
* Also replace duplication in `launchNewSessionWindow`
* Move `isDev()` from `main.js` to `helpers.js`
> chore: tune Electron window setups

- package-lock.json
- package.json
This is a fix for the change in #1544. It seems like the full Electron app (built via `electron-builder`) returns an error that redux-logger cannot be found. Moving it to main dependencies was confirmed to fix the issue, and the actual logs were also confirmed to still not be shown, as their initialisation is behind the development flag.
> fix: move redux-logger to main dependencies

- app/common/shared/i18next.config.js
- app/electron/main/windows.js
I noticed that i18next was returning some warnings when running it in debug mode. This PR fixes these warnings by ensuring that i18next has finished loading before it is used.
> chore: fix i18next warnings

- app/common/renderer/actions/Inspector.js
This PR fixes an issue where element search results were being added to the Recorder tab generated code, even when recording was turned off.
> fix: do not generate code for element searches if recording is turned off

- app/common/renderer/actions/Inspector.js
- app/common/renderer/components/Inspector/Commands.jsx
- app/common/renderer/components/Inspector/Inspector.jsx
- app/common/renderer/reducers/Inspector.js
This PR adds a new Redux state property `sessionSettings`, which stores the Appium settings for the currently active session. The stored settings are also updated if the user changes them through the Commands tab.
This information can be used for new features in the future (for example, to show an info bubble if the currently selected element is at `snapshotMaxDepth`).
> chore: store session settings in Redux

- app/common/public/locales/en/translation.json
- app/common/renderer/components/Inspector/LocatedElements.jsx
This is a fix for the info message added in #885.
The current implementation relies on the `disableIdLocatorAutocompletion` _capability_, not _setting_. This PR changes the check (and the info message) to use the setting instead.
> fix: retrieve disableIdLocatorAutocompletion from settings

- app/common/public/locales/en/translation.json
- app/common/renderer/components/Session/CapabilityEditor.jsx
- app/common/renderer/components/Session/SavedSessions.jsx
- app/common/renderer/components/Session/Session.module.css
Small PR to add a few missing button tooltips in the Session Builder screen:
* Deleting a single capability
* Adding a new capability
* Editing a capability set
* Deleting a capability set
The two buttons for capability set actions have also been merged using a button group, removing the space between them.
> fix: add missing tooltips in session builder

- app/common/public/locales/en/translation.json
- app/common/renderer/components/Inspector/Inspector.module.css
- app/common/renderer/components/Inspector/SelectedElement.jsx
This PR adds a new infobox when selecting an element located at `snapshotMaxDepth`. It helps users understand that some elements may be hidden, explains the reason why they are hidden, and provides a way to expose them.
The hope is that this infobox will also provide additional help for users testing React Native apps on iOS, since such apps [are known to have issues with high element depth](https://appium.github.io/appium-inspector/latest/troubleshooting/#cannot-see-full-source-tree-with-xcuitest-driver-react-native-app).
> feat: add infobox for elements at snapshotMaxDepth

- package.json
- renovate.json
Few changes to the Renovate config:
* Remove `transitiveRemediation` option since it has been removed in Renovate 38
* Split `schedule` into individual time points
* Add `cheerio`, `rimraf` and `uuid` to blocked major releases list
* Add group slug for Appium-related packages
> chore(renovate): adjust Renovate config

- renovate.json
One more minor adjustment for the Renovate config. Saw in the logs that `config:base` was changed to `config:recommended`. The former does not exist in the docs anymore, so it has been replaced with the latter.
> chore(renovate): tune Renovate config

- app/common/renderer/components/Inspector/SavedGestures.jsx
- app/common/renderer/components/Session/SavedSessions.jsx
This PR is a style change for the confirmation dialogs that appear when deleting a saved capability set or gesture.
* The current implementation uses the native browser alert/Electron full window popup, which blocks all interaction with the application until either of the two prompt options are selected.
* The proposed implementation switches to the `antd` `Popconfirm` component, which offers several benefits:
* More lightweight UX
* Consistent style with the rest of the app
* Automatically dismissed upon any action outside the dialog
* i18n support
Note: antd does not auto-hide tooltips on click, so for saved capability sets, the `zIndex` prop was used to place the tooltip behind the popconfirm.
> feat: replace native confirmation popups with antd popconfirms

- app/common/renderer/components/Session/Session.jsx
This small fix resolves an issue where the last opened server type tab was not being saved upon relaunching the app.
The reason is that `setSavedServerParams` checks the state variable `visibleProviders`, but this variable is empty until `setVisibleProviders` is called.
> fix: open most recent server type tab on app launch

- app/common/public/locales/en/translation.json
- app/common/renderer/components/Inspector/HeaderButtons.jsx
The tooltip for the quit session button incorrectly mentions that clicking it will also close the Inspector, but this is not the case. This PR removes this mention from the tooltip text.
> fix: adjust tooltip for quit session button

- app/common/renderer/components/Inspector/GestureEditor.jsx
Currently the gesture editor allows deletion of the default pointer in a gesture, which causes an odd-looking state (although it is easily recoverable). This PR simply prevents deleting the default pointer.
This works even if the user has a gesture where the default pointer had been previously deleted, since the `deletePointer` method automatically adjusts pointer IDs to always start at 1.
> fix: prevent deletion of default pointer in gesture

- app/common/renderer/components/Session/Session.module.css
There is a minor regression in 2024.6.1 where the capability set JSON contents can extend outside its container. This PR resolves this issue.
> fix: adjust saved session JSON height to fit in container

- app/common/renderer/components/Session/CapabilityEditor.jsx
Minor adjustment for #1597 - the tooltips for add/delete buttons were drawn over the delete buttons for other caps. This makes it inconvenient to delete multiple capabilites in a row, so the tooltip was changed to be shown on the right side of the buttons.
> fix: avoid overlap for add/delete capability button tooltips

- docs/session-inspector/gestures.md
Slight adjustment for the gesture docs - I noticed I had not updated them as part of #1623 (the gesture is now drawn on hover, not click).
> docs: tune gesture builder docs

- app/electron/main/windows.js
- docs/session-inspector/gestures.md
Accidentally noticed an issue where the customized macOS menu bar was sometimes not being loaded properly, which, among other things, would prevent changing the app language. I could not observe this in the dev or preview builds, only the full packaged app.
The problem is caused by the changes in #1574, but it is odd:
* before that PR, the menu was being built before i18n had finished, yet it worked fine
* after that PR, the menu was built after i18n had finished, but it seems to be having issues
* with this PR, the menu is built after the main Electron webcontents have finished (which happens after i18n finishes), and it somehow works fine again ¯\\\_(ツ)_/¯
> fix: resolve issue with incorrect app menu bar

- app/electron/main/windows.js
There is a known issue #286, where it is not possible to start a new session on a device accessed through Selenium Grid. This fixes the issue for the desktop app, by modifying the request header.
I'm also not sure whether this flow currently works through the browser version, because I was only getting CORS errors (even though I launched Appium, Selenium hub & Selenium node all with the allow-cors flag)
Thanks to @broetchenrackete36 for the code example in the linked issue, which was used as the basis for this fix.
Resolves #286.
> fix: allow creating sessions for Selenium Grid devices

- docs/contributing.md
While working on #1632, I noticed that I was unable to connect to Selenium Grid devices in the Inspector's dev mode, but it worked fine in production mode. The error I got in dev mode seemed to be related to CORS, so I got curious and tried to connect to a regular Appium server with CORS disabled - and I got the same error. Tried again with CORS enabled, and it worked as expected.
As this behavior is not immediately obvious, this PR adds a note in the contributing docs about the requirement to launch Appium with `--allow-cors` when in dev mode.
(I'm still unsure what additional configuration is needed for Selenium Grid, though - I launched Appium, Selenium Grid hub, and Selenium Grid node, all with CORS enabled, yet I was still getting the same error...)
> docs: add note about CORS in dev mode

- app/common/renderer/actions/Inspector.js
- app/common/renderer/utils/locator-generation.js
- app/common/renderer/utils/source-parsing.js
- package-lock.json
- package.json
- test/unit/utils-locator-generation.spec.js
- test/unit/utils-source-parsing.spec.js
`@xmldom/xmldom` `0.9.0` has a breaking change where it now requires the `mimeType` to be specified. This PR adds the MIME type, and also includes some additional refactoring for exporting only the DOMParser/XMLSerializer methods that are actually used, instead of their whole objects.
Tests were also confirmed to pass after updating to `@xmldom/xmldom` `0.9.0`.
> chore: adjust xmldom wrappers for xmldom 0.9

- app/common/renderer/components/ErrorBoundary/ErrorBoundary.jsx
- app/common/renderer/components/ErrorBoundary/ErrorMessage.jsx
- app/common/renderer/components/Inspector/HeaderButtons.jsx
- app/common/renderer/components/Inspector/Inspector.jsx
- app/common/renderer/components/Inspector/Recorder.jsx
- app/common/renderer/components/Inspector/SelectedElement.jsx
- app/common/renderer/components/Inspector/SessionCodeBox.jsx
- app/common/renderer/components/Session/Session.jsx
- app/common/renderer/polyfills.js
- app/electron/main/helpers.js
- app/electron/main/main.js
- app/electron/renderer/polyfills.js
- app/web/polyfills.js
This PR changes Electron's `shell` and `clipboard` modules to be only accessible through IPC. The goal of this change is to make these modules still operational without Electron's remote module, which is removed in Electron 14.
Note that these are not all of the modules that need to be converted: IPC will be required for most of the imports in `app/electron/renderer/polyfills.js`, and the remaining ones are as follows:
* `electron-settings`: possibly requires updating to v5
* Node's built-in `path`, `fs`, `util`: the latter two are only used for `.appiumsession` files, but they may not be required if session import/export is changed to match the import/export approach used for gestures
* `i18next-fs-backend`: not fully sure if this one needs IPC. May also require changing to …
> chore: convert Electron modules to IPC

- app/common/renderer/actions/Inspector.js
- app/common/renderer/actions/Session.js
- app/common/renderer/components/Inspector/Inspector.jsx
- app/common/renderer/components/Inspector/SavedGestures.jsx
- app/common/renderer/components/Session/CapabilityControl.jsx
- app/common/renderer/components/Session/CapabilityEditor.jsx
- app/common/renderer/constants/session-builder.js
- app/common/renderer/reducers/Session.js
- app/common/renderer/utils/file-handling.js
- app/common/renderer/utils/other.js
- app/electron/main/helpers.js
- app/electron/renderer/polyfills.js
This is a small refactor in preparation for adjustments to session file handling. These adjustments are already made in a separate branch, but the branch includes too many changes that could be extracted, therefore I made this PR.
Changes made:
* Adjust Electron IPC calls to include scope (basically just replace `-` with `:`)
* Rename redux event `SET_STATE_FROM_SAVED` to `SET_STATE_FROM_FILE`
* Add a dedicated constant for the types that a capability value can take
* Move file handler util methods from `other.js` to a new `file-handling.js` file
> chore: refactor in preparation for session file handling changes

- app/common/public/locales/en/translation.json
- app/common/renderer/actions/Session.js
- app/common/renderer/components/Session/Session.jsx
- app/common/renderer/polyfills.js
- app/common/renderer/reducers/Session.js
- app/common/renderer/utils/file-handling.js
- app/electron/main/helpers.js
- app/electron/main/main.js
- app/electron/main/menus.js
- app/electron/main/windows.js
- app/electron/renderer/polyfills.js
- app/web/polyfills.js
- test/unit/utils-file-handling.spec.js
This PR includes a few refactors for handling `.appiumsession` files. Currently there are 3 main flows related to them:
* saving the current session details into a downloadable `.appiumsession` file
* selecting an `.appiumsession` file from the File menu and loading its contents
* if the app is not running, opening an `.appiumsession` file directly, which opens the Inspector with the session file contents loaded
The changes in this PR do not attempt to overhaul these flows, but only refactor their implementation, with the main goal of removing the `fs` and `util` polyfills from the renderer process, as this would simplify the eventual Electron upgrade.
However, there are still a few improvements to the importing flows:
* enhanced validation when importing a session file (plus tests for …
> chore: refactor session file handling

- app/common/renderer/i18next.js
- app/common/renderer/polyfills.js
- app/electron/main/helpers.js
- app/electron/renderer/polyfills.js
- app/web/polyfills.js
- vite.config.mjs
This PR continues the move to IPC by migrating `electron-settings`.
Since the renderer process would now always need to wait for a response from the main process, the `getSettingSync` call for `i18next` was changed to `await getSetting`. However, top-level awaits are supported only by a subset of the default Vite browser target set, so the browser build target was changed to `es2022`. This should not affect most users - all major browsers have support for top-level await since September 2021.
Changes were tested to still work in Electron/browser production builds, as well as the packaged Electron app on macOS & Windows.
> chore: move electron-settings to IPC

- app/common/renderer/components/Inspector/Inspector.module.css
- app/common/renderer/components/Session/Session.module.css
- app/electron/main/windows.js
- docs/quickstart/requirements.md
- docs/troubleshooting.md
- package-lock.json
- package.json
- renovate.json
This PR (finally) upgrades Electron all the way to the second latest version 31.4.0! ⚡
(latest version 32 has [some known dev-specific issues](https://github.com/electron/electron/issues/43415))
Seems like the only blocker for this was the remote module, the need for which has been eliminated with the IPC migration PRs. I started with Electron 14, and when that worked fine, I continued iterating through every major version, checking whether the app launches fine in dev mode. For Electron 31, I also checked preview and packaged app versions, and tested out basic things like session creation, element selection via screenshot, and element search.
However, every Electron version comes with some breaking changes, and some of them also affect Inspector. The most relevant of these are related to …
> chore(deps): upgrade Electron to 31.4.0

- package-lock.json
- package.json
- renovate.json
This is a simple bump for dependencies whose updates were blocked solely due to them dropping Node 14.
Since `rimraf` now requires Node 20, the `engines` field was adjusted accordingly. The `devEngines` field was also removed since it is not standard and requires additional scripts to be useful.
> chore: update electron-debug, highlight.js, rimraf

- app/common/renderer/constants/session-inspector.js
- app/common/renderer/lib/appium-client.js
- app/common/renderer/utils/file-handling.js
- ci-jobs/crowdin-update-resources.mjs
- package-lock.json
- package.json
This PR replaces all uses of `bluebird` with native JS promises. It has not been updated in nearly 5 years, and its readme recommends using native promises anyway.
> chore: remove bluebird dependency

- app/common/renderer/components/Inspector/Screenshot.jsx
This PR fixes some issues when using the screenshot Coordinates Mode:
* If the user taps or swipes on the screenshot, then, while the action is being executed, moves a mouse to another location and attempts a tap or swipe again, the new mouse position was not updated
* If the user clicks and holds to start a swipe action, then moves the mouse outside the screenshot bounds, the swipe action was not canceled
* If the user moves the mouse outside the screenshot bounds, the coordinates overlay values were not cleared
A side-effect of these changes is that the circle/line drawn over the screenshot as part of the tap/swipe action is now dismissed as soon as the screenshot loading overlay appears, instead of after the action finishes. This does not affect MJPEG mode since the loading overlay is …
> fix: resolve some screenshot Coordinates Mode issues

- app/common/renderer/components/Inspector/Inspector.jsx
This PR fixes the issue where element highlighters over the screenshot were sometimes drawn over incorrect coordinates. This commonly happened when starting a session directly into landscape mode, or resizing the Inspector window height (not width). The underlying cause was that the scale ratio for drawing highlighters was using old data.
The overall implementation has also been slightly simplified, and the unnecessary 500ms debounce was removed, so now the highlighter update is subject to the same 50ms debounce used for calculating the screenshot scale - it feels much more responsive.
Fixes #1680.
> fix: adjust calculation of element highlighter positions

- app/common/renderer/components/Inspector/Inspector.module.css
Small PR to fix #1691. The `z-index` of antd modals is set to 1000, but several other elements had a higher `z-index` value and were therefore intercepting interactions with the modal (specifically, `swipeSvg`).
This also removes the style for an unused `tapDiv` class.
> fix: prevent Coordinates Mode from intercepting modals

- .github/workflows/package.yml
Trying to move https://github.com/appium/appium-inspector/blob/main/ci-jobs/templates/package.yml to GHA.
I'll keep `never` in `npx electron-builder build` until these are ready.
This is an initial PR to run this package.yml action manually to test the package.yml out, so I'll merge this after CI pass for now.
cc @eglitise @jlipps
> ci: add initial creating package GHA

- electron.vite.config.mjs
This PR fixes a problem with building the app in dev mode due to an error from `i18next-fs-backend`. The problem first appeared after #1802, where a top-level await was added in the dependency code.
The issue did not seem to affect the app's preview build, and it does not affect the browser version, as this dependency is not used there.
> chore: fix dev mode error from i18next-fs-backend

- app/common/renderer/Root.jsx
- app/common/renderer/components/Inspector/Inspector.jsx
- app/common/renderer/components/Session/Session.jsx
- package-lock.json
- package.json
Same as #1807, with the package and its imports also renamed to `react-router`.
> chore(deps): update react-router-dom to v7 and rename it

- package.json
- renovate.json
This PR extends the Renovate blacklist with a few more packages whose updates are currently blocked for one reason or another. It also adds all of these packages to the comments list in `package.json`, so that both lists are now in sync.
> chore: add more packages to Renovate's blocklist

- plugins/index.mjs
- plugins/package.json
This PR does:
- Update https://www.npmjs.com/package/appium-inspector-plugin
Fixed
```
$ appium plugin install --source=npm appium-inspector-plugin@2024.12.1-beta.1
✔ Checking if 'appium-inspector-plugin' is compatible
✖ Installing 'appium-inspector-plugin@2024.12.1-beta.1'
Error: ✖ Encountered an error when installing package: Package subpath './package.json' is not defined by "exports" in /Users/kazu/.appium/node_modules/appium-inspector-plugin/package.json
```
Fixed below as well, but I needed to add `dependencies`...
```
[Appium] Could not load plugin 'inspector', so it will not be available. Error in loading the plugin was: Cannot find package 'appium' imported from /Users/kazu/.appium/node_modules/appium-inspector-plugin/index.mjs
[Appium] Error: Cannot find package 'appium' …
```
> feat: add beta for testing and npm available

- eslint.config.mjs
- package-lock.json
- package.json
This PR removes the `.gitignore` file-related code from the ESLint config, since this functionality is handled by `@appium/eslint-config-appium-ts` `>=1.0.2`. This change also allows to remove the explicit dependency on `@eslint/compat`.
> chore: tidy up ESLint config

- app/electron/main/updater.js
ESLint's suggested import syntax for `electron-updater` unfortunately prevents the app from being launched in both dev and production modes:
```
SyntaxError: Named export 'autoUpdater' not found. The requested module 'electron-updater' is a CommonJS module, which may not support all module.exports as named exports.
```
This PR reverts to the previous syntax, which is also provided as a recommendation in the error message.
> chore: revert import syntax for updater

- app/electron/main/debug.js
- package-lock.json
- package.json
I noticed that the previously-used `electron-devtools-installer` recently got an update after 3 years. Since it is maintained by Electron maintainers, it seems better in the long run to switch back to it.
Also, since its README suggested installing it as a dev dependency, I checked the app functionality in dev and preview builds, and it worked fine.
Finally, the `allowFileAccess: true` option was removed, since Electron's `loadFile()` method is not used in dev mode, which is the only scope of relevance for this package. Extensions were confirmed to still load fine.
> chore: change devtools dependency & move it to dev dependencies

- app/common/renderer/actions/Session.js
- app/common/renderer/utils/attaching-to-session.js
- test/unit/utils-attaching-to-session.spec.js
This PR adds support for retrieving and attaching to existing sessions in Appium 3, which will use the `/appium/sessions` endpoint (see https://github.com/appium/appium/issues/20880). If such sessions are found, they will also have the session ID (shown in their dropdown entry) replaced with the session creation timestamp.
Compatibility with Appium 1-2 and Selenium Grid sessions remains unchanged, although all 3 endpoints are now queried in parallel for better performance.
> feat: add support for Appium 3 session retrieval

- package.json
- renovate.json
Now that there are no more blockers for Vite v6, it should be safe to remove from Renovate's blocklist.
> chore(deps): remove vite from Renovate blocklist

- package-lock.json
- package.json
- plugins/package.json
Seems like Renovate has some issues with the latest Appium package version bump - my guess is because of a mismatch between the current versions of `base-plugin` in the lockfile and `plugins/package.json` (even though they do not affect each other). This PR updates the packages and also rebuilds the entire lockfile (using `npm run clean:npm`)
If this happens again in the future, we'll look for another solution.
> chore(deps): update appium-related packages & rebuild lockfile

- LICENSE
The text contents were directly copied from the Appium repo's LICENSE file.
> chore: update LICENSE to use full AL2.0 text

- app/common/renderer/components/Inspector/Recorder.jsx
- app/common/renderer/components/Inspector/SessionCodeBox.jsx
This fixes a small issue I noticed while refactoring the framework-related code:
* Open the Recorder tab, then switch to Session Information tab
* Change the selected client framework to any other
* Switch back to Recorder -> selected dropdown value is still for the previous framework
This PR ensures that the selected dropdown value is shared between both dropdowns.
> fix: ensure selected client framework dropdown values are in sync

- renovate.json
Seems like Renovate gets a bit confused due to the `@appium/base-plugin` dependency in the plugin's `package.json` file. Let's try to update that separately from other Appium packages, and leave the common lockfile unchanged.
I've also extended the blocklist with other React-related packages, since they are blocked similarly to the main package.
> chore(deps): adjust Renovate for base-plugin package.json

- plugins/package.json
to avoid:
```
✖ Checking if 'appium-inspector-plugin' is compatible
Error: ✖ 'inspector' cannot be installed because the server version it requires (^2.0.0) does not meet the currently installed one (3.0.0-beta.0). Please install a compatible server version first.
```
in the install command. So far, we don't have breaking changes related to this plugin.
> chore: add '|| ^3.0.0-beta.0' to plugin

- package-lock.json
As usual, rebuilding the lockfile with `npm run clean:npm`.
> chore: rebuild lockfile

- README.md
- docs/contributing.md
- docs/overview.md
- docs/quickstart/index.md
- docs/quickstart/installation.md
- docs/quickstart/requirements.md
- docs/quickstart/starting-a-session.md
- docs/session-builder/server-details.md
- package.json
- plugins/README.md
As the Inspector's plugin version is now official, it makes sense to update the docs to reflect this.
The technical details of the plugin's README have also been moved into the main documentation, and the Appium 1-related mentions have been removed due to it being unsupported.
> docs: add plugin-related information

- app/common/renderer/actions/Inspector.js
- app/common/renderer/components/Inspector/HeaderButtons.jsx
- docs/quickstart/installation.md
- docs/quickstart/requirements.md
Small PR to replace 2 more server commands that will be removed in Appium 3 (see #2016). Some related documentation has also been updated.
* Replace `getCurrentPackage` and `pressKeyCode` methods with their `mobile:` equivalents
* All four changes were confirmed to work
* This leaves only `getSession` as the last used method that will be removed in Appium 3
* Add more details in documentation about the recommended driver versions
* The specified versions added support for `mobile:getSystemBars` / `mobile:deviceScreenInfo`
* Fix indentation in the plugin install instructions
> chore: replace more endpoints removed in Appium 3

- app/common/renderer/components/Inspector/GestureEditor.jsx
- app/common/renderer/components/Inspector/HeaderButtons.jsx
- app/common/renderer/components/Inspector/Inspector.jsx
- app/common/renderer/components/Inspector/LocatedElements.jsx
- app/common/renderer/components/Inspector/Recorder.jsx
- app/common/renderer/components/Inspector/SavedGestures.jsx
- app/common/renderer/components/Inspector/SelectedElement.jsx
- app/common/renderer/components/Session/SavedSessions.jsx
Refactor according to console warning since upgrading to antd v5 (https://github.com/appium/appium-inspector/pull/2123): 
`[antd: Button.Group] Button.Group is deprecated. Please use Space.Compact instead.`
No changes to UI as far as I could tell.
> refactor: button group to space compact

- app/common/renderer/components/Inspector/Commands.jsx
- app/common/renderer/components/Inspector/SavedGestures.jsx
- app/common/renderer/components/Session/AdvancedServerParams.jsx
Refactor according to console warning since upgrading to antd v5 (https://github.com/appium/appium-inspector/pull/2123): 
`[rc-collapse] children will be removed in next major version. Please use items instead.`
No changes to UI as far as I could tell.
> refactor: collapse usage

- app/common/renderer/Root.jsx
- app/common/renderer/actions/Session.js
- app/common/renderer/components/Inspector/Commands.jsx
- app/common/renderer/components/Inspector/GestureEditor.jsx
- app/common/renderer/components/Notification.jsx
- app/common/renderer/utils/notification.js
Refactor according to console warning since upgrading to antd v5 (https://github.com/appium/appium-inspector/pull/2123): 
`[antd: notification] Static function can not consume context like dynamic theme. Please use App component instead.`
Now using `notification` from `App.useApp()`. It's recommended by antd to use hooks instead of the static notification method (https://ant.design/components/notification). Notifications are triggered by dispatching an event which are picked up by the `Notification` component listener.
> refactor: notification to hooks usage

- docs/quickstart/starting-a-session.md
- package-lock.json
- package.json
Same as #2140 but with the additional changes resulting from running Prettier (just one deleted empty line in the docs, which has no effect on the generated page)
> chore(deps): update prettier to v3.6.0

- app/common/renderer/components/Session/CapabilityEditor.jsx
Randomly stumbled upon this bug: after starting and closing a session, then switching to another saved caps set with a different number of capabilities, the app throws an error. Not reproducible on 2025.3.1, so it may be related to antd v5.
The fix here just adds an extra guard to validate that `latestCapField.current` is set before attempting to access its properties. The `__didFocus` property checks were also removed, as they did not change the expected behavior (autofocusing upon adding a new capability)
> fix: resolve error when switching saved caps set after closing session

- app/common/renderer/components/Inspector/GestureEditor.jsx
Quick fix to adjust some deprecated `antd` properties in the gesture editor:
> chore: adjust deprecated antd properties

- app/common/renderer/actions/Session.js
- vite.config.mjs
Slight security improvement for the browser version. Currently Vite is configured to pass the entire `process.env` object to the build, which is unneeded. However, it's not a critical issue because the object is only exposed in the dev build (I checked both the preview build and inspector.appiumpro.com).
This PR simply changes it to an empty object, eliminating the Vite build warning.
A similar adjustment is added for `process.argv`, which also eliminates one console error.
> fix: do not pass process value to browser build

- app/common/renderer/constants/commands.js
- app/common/renderer/lib/client-frameworks/dotnet-nunit.js
- app/common/renderer/lib/client-frameworks/java-common.js
- app/common/renderer/lib/client-frameworks/js-oxygen.js
- app/common/renderer/lib/client-frameworks/js-wdio.js
- app/common/renderer/lib/client-frameworks/python.js
- app/common/renderer/lib/client-frameworks/robot.js
- app/common/renderer/lib/client-frameworks/ruby.js
This PR adds 3 new commands to the Commands list, that can be used to retrieve current session information:
* `getAppiumCommands`
* `getAppiumExtensions`
* `getAppiumSessionCapabilities`
In order to use these commands, the following are required:
* Appium `>= 2.16.0`
* UiAutomator2 driver `>= 4.2.6` or XCUITest driver `>= 8.3.2`
> feat: add commands to retrieve session commands, extensions & caps

- app/common/renderer/assets/stylesheets/main.css
- app/common/renderer/components/Inspector/Source.jsx
Small PR to add a useful feature in the antd Tree component - showing lines between sibling nodes in the source tree. I've also included a minor CSS fix for the tree node expand/collapse icon, since it was vertically misaligned.
For a comparison, this is how a tree might look currently:
This is how the same tree looks after these changes:
> feat: show lines between source tree nodes

- app/common/renderer/components/Session/CapabilityEditor.jsx
- app/common/renderer/components/Session/SavedSessions.jsx
- app/common/renderer/components/Session/Session.module.css
This PR is a follow-up to #2196 and adds the antd Splitter component for the Session Builder as well.
* The Capability Builder tab now supports collapsing either the fields or JSON panels. Resizing is intentionally disabled due to CSS issues with the form fields.
* I also adjusted the form field column widths, making the capability name and value fields larger
* The Saved Capability Sets tab now supports resizing the saved sets and JSON structure panels, as well as collapsing the JSON structure panel. Collapsing for the saved sets is intentionally disabled since it doesn't really make sense.
Here is a brief demo:
https://github.com/user-attachments/assets/296b0415-57b3-4fce-9536-0fd3e4eeda4a
> feat: allow resizing/collapsing session builder panels

- package-lock.json
- package.json
This should prevent Renovate from removing dependencies required for linting.
> chore(deps): bump eslint-config-appium-ts to 2.0.0-rc.1

- package.json
- plugins/package.json
Replaces #2255. The required Node.js and Appium versions have been adjusted to match those of `@appium/base-plugin` `3.0.0`, meaning the plugin version will no longer be compatible with Appium 2.
> chore: set plugin requirements to Appium 3

- docs/quickstart/installation.md
Slight refresh of the installation docs:
* Update commands for installing the plugin for both Appium 2 and 3
* Use material-mkdocs collapsible blocks to wrap workaround steps for Win/Mac
* Add unofficial installation methods for WinGet and Homebrew (I couldn't find any Linux package managers hosting the Inspector)
> docs: update installation steps

- .github/labeler.yml
- .github/release.yml
Since this is a GUI application, it is possible to have PRs that simply adjust the existing GUI, without any functionality changes (such as #2265). The new `style` label is meant for this exact purpose, and this PR adds handling of this label for the autolabeler and release notes generator actions.
> chore: add style label support to autolabeler & release notes

- .gitignore
- plugins/index.mjs
I missed the fact that the plugin version had to be adjusted for Express 5, similarly to https://github.com/appium/appium/pull/20789.
Tested this locally and it works fine.
Fixes #2284
> fix: adjust plugin version Express paths

- app/common/renderer/components/ErrorBoundary/ErrorBoundary.jsx
- app/common/renderer/components/ErrorBoundary/ErrorMessage.jsx
- app/common/renderer/components/Notification.jsx
- app/common/renderer/hooks/use-theme.jsx
- app/common/renderer/i18next.js
- app/common/renderer/polyfills.js
- app/common/renderer/providers/ThemeProvider.jsx
- app/common/renderer/store.js
- app/common/renderer/utils/attaching-to-session.js
- app/common/renderer/utils/file-handling.js
- app/common/renderer/utils/locator-generation.js
- app/common/renderer/utils/other.js
- app/common/shared/setting-defs.js
- app/electron/main/helpers.js
- app/electron/main/i18next.js
- app/electron/main/main.js
- app/electron/main/menus.js
- app/electron/main/updater.js
- app/electron/main/windows.js
- test/e2e/inspector-e2e.test.js
- test/e2e/pages/inspector-page-object.js
- test/unit/utils-attaching-to-session.spec.js
- test/unit/utils-file-handling.spec.js
- test/unit/utils-locator-generation.spec.js
- test/unit/utils-other.spec.js
- test/unit/utils-source-parsing.spec.js
- test/unit/utils-webview.spec.js
Some file imports were missing the `.js`/`.jsx` extension, which prevented VS Code IntelliSense from working properly.
> chore: add js/jsx extensions to all imported files
